services:
    mf_web:
        build:
            context: ./mf_web/init
        ports:
            - "${WEB_EXT_PORT}:80"
        volumes:
            - ./mf_web/volumes/htdocs/:/var/www/localhost/htdocs/
            - ./mf_web/volumes/lighttpd/:/etc/lighttpd/
        tty: true
        links:
            - mf_db
    mf_db:
        image: mariadb:11.0
        ports:
            - "${DB_EXT_PORT}:3306"
        environment:
            - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
