services:
    mf_web:
        build:
            context: ./mf_web/init
            # args:
            #     conf_path: ${CONF_PATH}@
        ports:
            - "${WEB_EXT_PORT}:80"
        volumes:
            - ./mf_web/volumes/htdocs/:/var/www/localhost/htdocs/
            - ./mf_web/volumes/lighttpd/:/etc/lighttpd/
        tty: true
        links:
            - mf_db
    mf_db:
        image: mariadb:10
        ports:
            - "${DB_EXT_PORT}:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
