name: mf_dcpn
services:
    web_app_dsn:
        build:
            context: ./web_app
        ports:
            - "${MF_WEB_PORT_EXT:?error}:80"
        volumes:
            - ./web_app:/var/www/html
        tty: true
        links:
            - db_dsn
    db_dsn:
        image: mariadb:11.0
        ports:
            - "${MF_DB_PORT_EXT:?error}:3306"
        environment:
            - MARIADB_ROOT_PASSWORD=${MF_DB_PWD:?error}
