services:
    web_server_dcn:
        build:
            context: ./docker/web_server
        ports:
            - "${WEB_EXT_PORT}:80"
        volumes:
            - ./src/:/var/www/html/
        tty: true
        links:
            - db_dcn
    db_dcn:
        image: mariadb:11.0
        ports:
            - "${DB_EXT_PORT}:3306"
        environment:
            - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
