services:
    web_server_dcn:
        build:
            context: ./docker/web_server
        ports:
            - "${MF_WEB_PORT_EXT:?error}:80"
        volumes:
            - ./src/:/var/www/html/
        tty: true
        links:
            - db_dcn
    db_dcn:
        image: mariadb:11.0
        ports:
            - "${MF_DB_PORT_EXT:?error}:3306"
        environment:
            - MARIADB_ROOT_PASSWORD=${MF_DB_PWD:?error}
