services:
    mf_web:
        build:
            context: ./mf_web/init
        ports:
            - "${WEB_EXT_PORT}:80"
        volumes:
            - ./mf_web/src/:/var/www/html/src/
        tty: true
        links:
            - mf_db
    mf_db:
        image: mariadb:11.0
        ports:
            - "${DB_EXT_PORT}:3306"
        environment:
            - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
