<?php

namespace MF\Model;

use MF\Enum\ModelPropertyType;


class ArticleDefinition implements ModelDefinition
{
    public function getName(): string {
        return 'article';
    }

    public function getProperties(): array {
        return [
            new ModelProperty(
                'id',
                ModelPropertyType::VARCHAR,
                autoGenerated: true,
            ),
            new ModelProperty('author_id', ModelPropertyType::VARCHAR, autoGenerated: true),
            new ModelProperty('category_id', ModelPropertyType::VARCHAR),
            new ModelProperty('body', ModelPropertyType::TEXT),
            new ModelProperty('is_featured', ModelPropertyType::BOOL),
            new ModelProperty('title', ModelPropertyType::VARCHAR),
            new ModelProperty('cover_filename', ModelPropertyType::IMAGE),
            new ModelProperty('creation_date_time', ModelPropertyType::DATETIME, autoGenerated: true),
            new ModelProperty('last_update_date_time', ModelPropertyType::DATETIME, autoGenerated: true),
        ];
    }
}