name: Automated GitHub testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create the Docker configuration file
        run: cp .env.dist .env

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Create folder for uploaded images
        run: docker-compose exec -T -u www-data web_server_dcn mkdir public/uploaded

      - name: Install Composer dependencies
        run: docker-compose exec -T web_server_dcn composer install

      - name: Generate style.css
        run: docker-compose exec -T web_server_dcn ./sass.sh

      - name: Create configuration
        run: docker-compose exec -T web_server_dcn cp .env.json.dist .env.json.local

      - name: Populating the database with fixtures
        run: docker-compose exec -T web_server_dcn ./fixtures.sh

      - name: Running integration test
        run: docker-compose exec -T web_server_dcn ./tests.sh