on: [push]
jobs:
  build-services:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker images and start the containers
        run:
          - cp .env.dist .env
          - cp mf_web/volumes/htdocs/.env.json.dist mf_web/volumes/htdocs/.env.json
          - docker-compose up -d