on: [push]
jobs:
  build-services:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Create the Docker configuration file
        run: cp .env.dist .env
      - name: Run the Docker Compose script
        run: DOCKER_BUILDKIT=1 docker-compose up -d
      - name: Create folder for uploaded images
        run: docker-compose exec -T -u www-data web_server_dcn mkdir public/uploaded
      - name: Install Composer dependencies
        run: docker-compose exec -T web_server_dcn composer install
      - name: Generate style.css
        run: docker-compose exec -T web_server_dcn ./sass.sh
      - name: Create configuration
        run: docker-compose exec -T web_server_dcn cp .env.json.dist .env.json.local
      - name: Populating the database with fixtures
        run: docker-compose exec -T web_server_dcn ./fixtures.sh
      - name: Running integration test
        run: docker-compose exec -T web_server_dcn ./tests.sh