on: [push]
jobs:
  build-services:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Create the Docker configuration file
        run: cp .env.dist .env
      - name: Run the Docker Compose script
        run: DOCKER_BUILDKIT=1 docker-compose up -d
      - name: Install Composer dependencies
        run: docker-compose exec -T mf_web composer install
      - name: Generate style.css
        run: docker-compose exec -T mf_web ./sass.sh
      - name: Create configuration
        run: docker-compose exec -T mf_web cp .env.json.dist .env.json.local
      - name: Populating the database with fixtures
        run: docker-compose exec -T mf_web ./fixtures.sh
      - name: Running integration test
        run: docker-compose exec -T mf_web ./tests.sh