on: [push]
jobs:
  build-services:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Create the Docker configuration file
        run: cp .env.dist .env
      - name: Create the web app configuration file
        run: cp mf_web/volumes/htdocs/.env.json.dist mf_web/volumes/htdocs/.env.json
      - name: Run the Docker Compose script
        run: DOCKER_BUILDKIT=1 docker-compose up -d
      - name: Install Composer dependencies
        run: docker-compose exec -T mf_web composer install
      - name: Generate style.css
        run: docker-compose exec -T mf_web vendor/bin/pscss sass/style.scss public/style.css
      - name: Running basic tests
        run: docker-compose exec -T mf_web php -f scripts/tests.php